# Generated by Django 5.0.3 on 2024-04-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datachange',
            name='data',
            field=models.CharField(default=True, max_length=10),
        ),
    ]
